services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./api"]
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/bookings_db?sslmode=disable
    depends_on:
      - db

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./migrate"]
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/bookings_db?sslmode=disable
    depends_on:
      - db

  schedule:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./schedule"]
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/bookings_db?sslmode=disable
    depends_on:
      - migrate

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookings_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "bookings_db" ]
      interval: 10s
      retries: 5

volumes:
  db_data: